branches:
  only:
  - master

language: node_js

notifications:
  email:
  - nttdocomo.ouyi@gmail.com

node_js:
  - 'stable'

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - |
          npm test -- --coverage && \
          bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      name: "Deploy"
      script:
        - |
          npm run semantic-release

# NPM_TOKEN=88a4ce2e-5209-4419-92c3-ba7708cd93cb
# GH_TOKEN=0c057280596d851a9a3a16a39e6a5db3ef58cdfe