branches:
  only:
  - master

language: node_js

notifications:
  email:
  - nttdocomo.ouyi@gmail.com

node_js:
  - 'stable'


jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      before_install:
        - |
          if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/'
          then
            echo "Only docs were updated, stopping build process."
            exit
          fi
      script:
        - |
          if [ "$TEST_TYPE" = test ]; then
            npm test -- --coverage && \
            bash <(curl -s https://codecov.io/bash)
          else
            npm run $TEST_TYPE
          fi
      env:
        matrix:
        - TEST_TYPE=lint
        - TEST_TYPE=test
    - stage: deploy
      name: "Deploy"
      script:
        - |
          echo $GH_TOKEN
          npm run semantic-release
      env:
        - GH_TOKEN=2e66b0882c480c7aac64b83c36bc8b4f6ae0a689
  

  # 2e66b0882c480c7aac64b83c36bc8b4f6ae0a689